#ifndef BUILD_SETTINGS_HPP
#define BUILD_SETTINGS_HPP

#define CONTROL_BAR_WIDTH 300
#define WINDOW_WIDTH_START 1200
#define WINDOW_HEIGHT_START 600
#define FOV_HEIGHT_DEGREES_START 60.0
#define LATITUDE_START -0.0959931089 // start camera facing at Orion Constellation
#define LONGITUDE_START 1.45937
#define LONGITUDE_SCROLL_RATE 0.4
#define LATITUDE_SCROLL_RATE 0.4
#define VSYNC_START false
#define SHOW_ACCRETION_DISK_START true
#define FPS_REFRESH_TIME 1.0
#define MAX_R_S 5.0
#define MAX_R_CAMERA 100.0
#define INITIAL_R_CAMERA 20.0
#define MIN_LOG10_TIMESTEP_SCALE -4.0
#define MAX_LOG10_TIMESTEP_SCALE 1.0
#define INITIAL_LOG10_TIMESTEP_SCALE -2.5
#define MAX_MAXSTEPS 10000
#define INITIAL_MAXSTEPS 5500
#define UI_ITEM_SPACING 10
#define UI_PADDING 10
#define MAX_ACCRETION_DISK_SIZE 50.0
#define INITIAL_ACCRETION_DISK_SIZE 12.0
#define MIN_DOWNSAMPLE_RATE 0.5
#define MAX_DOWNSAMPLE_RATE 5.0
#define INITIAL_DOWNSAMPLE_RATE 1.5
#define INITIAL_DO_RGB false
#define MAX_RGB_PERIOD 60.0
#define INITIAL_RGB_PERIOD 30.0
#define INITIAL_ACCRETION_DISK_FREQUENCY 1.0
#define MAX_ACCRETION_DISK_FREQUENCY 10.0
#define RGB_BRIGHTNESS 2.0f
#define RGB_OPACITY 4.0f
#define NORGB_BRIGHTNESS 14.0f
#define NORGB_OPACITY 4.0f

#define VERTEX_SHADER_PATH "shaders/vertex_shader.glsl"
#define FRAGMENT_SHADER_PATH "shaders/fragment_shader.glsl"
//#define STARMAP_PATH "resources/TychoSkymapII.t5_08192x04096.jpg"
#define STARMAP_PATH "resources/TychoSkymapII.t3_04096x02048.jpg"
//#define STARMAP_PATH "resources/TychoSkymapII.t5_04096x02048.jpg"
//#define STARMAP_PATH "resources/checkerboard.jpg"
#define DISK_RING_PATH "resources/disk.jpg"

#endif